backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"   # where uploaded images go
public_folder: "/uploads"        # how they’re referenced in your site

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"      # adjust if your markdown lives elsewhere
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body",  name: "body",  widget: "markdown" }
